version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - supabase
      - redis

  supabase:
    image: supabase/supabase:latest
    ports:
      - "54321:54321"
      - "54322:54322"
    volumes:
      - supabase-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  supabase-data:
  redis-data:
